create database campus_uf
create table aluno(
id_aluno char (3)not null, 
nome varchar (30),
constraint pk_aluno primary key (id_aluno),
);
create table professor (
id_prof char (3) not null,
nome varchar (30),
constraint pk_professor primary key (id_prof),
);
create table sala (
id_sala char (3)not null,
numero integer ,
constraint pk_sala primary key (id_sala),
);
create table curso(
id_curso char (3)not null,
nome varchar (30) ,
id_sala char (3)not null,
constraint pk_curso primary key (id_curso),
constraint fk_curso_sala foreign key (id_sala)references sala (id_sala),
);
CREATE TABLE ALOCACAO (
id_prof char (3)not null,
 ID_CURSO CHAR(3) NOT NULL, 
 CONSTRAINT PK_ALOCACAO PRIMARY KEY (ID_PROF, ID_CURSO), 
 CONSTRAINT FK_ALOCACAO1_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO), 
CONSTRAINT FK_ALOCACAO2_PROFE FOREIGN KEY (ID_PROF) REFERENCES PROFESSOR
(ID_PROF) ON DELETE CASCADE
);
create table turma (
id_curso char (3) not null,
id_turma char (3)not null,
constraint pk_turma1_curso primary key(id_curso,id_turma),
constraint fk_turma1_curso foreign key (id_curso)references curso (id_curso) on delete cascade
);
CREATE TABLE AULA (
ID_PROF CHAR(3) NOT NULL, 
ID_CURSO CHAR(3) NOT NULL, 
ID_TURMA CHAR(3) NOT NULL, 
DIA INTEGER, HORA INTEGER, 
CONSTRAINT PK_AULA PRIMARY KEY (ID_PROF, ID_CURSO, ID_TURMA), 
CONSTRAINT FK_AULA1_TURMA FOREIGN KEY (ID_CURSO, ID_TURMA) REFERENCES TURMA
(ID_CURSO, ID_TURMA) ON DELETE CASCADE, CONSTRAINT FK_AULA2_PROFE FOREIGN KEY (ID_PROF) REFERENCES PROFESSOR (ID_PROF)
ON DELETE CASCADE
);
CREATE TABLE INSCRICAO (
ID_CURSO CHAR(3) NOT NULL,
 ID_TURMA CHAR(3) NOT NULL, 
 ID_ALUNO CHAR(3) NOT NULL,
  CONSTRAINT PK_INSCRICAO PRIMARY KEY (ID_CURSO, ID_TURMA, ID_ALUNO), 
  CONSTRAINT FK_INSCRICAO1_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO
(ID_ALUNO) ON DELETE CASCADE, CONSTRAINT FK_INSCRICAO2_TURMA FOREIGN KEY (ID_CURSO, ID_TURMA) REFERENCES
TURMA (ID_CURSO, ID_TURMA) ON DELETE CASCADE
);

INSERT INTO SALA (id_sala, numero) VALUES ('S1 ', 10);
INSERT INTO SALA (ID_SALA, numero) VALUES ('S2 ', 15);
INSERT INTO SALA (ID_SALA, numero) VALUES ('S3 ', 8);




INSERT INTO CURSO (id_curso, NOME, id_sala) VALUES ('01 ', 'WORD', 'S1' );
INSERT INTO CURSO (id_curso, NOME, id_SALA) VALUES ('02 ', 'EXCEL', 'S1 ');
INSERT INTO CURSO (id_curso, NOME, id_sala) VALUES ('03 ', 'LINUX', 'S2 ');
INSERT INTO CURSO (id_curso, NOME, id_sala) VALUES ('04 ', 'POWERPOINT', 'S3 ');
INSERT INTO CURSO (id_curso, NOME, id_sala) VALUES ('05 ', 'COREL', 'S3 ');
INSERT INTO CURSO (id_curso, NOME, id_sala) VALUES ('06 ', 'ACCESS', 'S3 ');

INSERT INTO PROFESSOR (id_prof, NOME) VALUES ('01 ', 'LUIZ');
INSERT INTO PROFESSOR (id_prof, NOME) VALUES ('02 ', 'ANA LUCIA');
INSERT INTO PROFESSOR (id_prof, NOME) VALUES ('03 ', 'CLAUDIO');
INSERT INTO PROFESSOR (id_prof, NOME) VALUES ('04 ', 'ALOISIO');

INSERT INTO ALOCACAO (id_prof, id_CURSO) VALUES ('01 ', '01 ');
INSERT INTO ALOCACAO (id_prof, id_CURSO) VALUES ('01 ', '02 ');
INSERT INTO ALOCACAO (id_prof, id_CURSO) VALUES ('02 ', '03 ');


INSERT INTO SALA (id_sala, numero) VALUES ('S1 ', 10);
INSERT INTO SALA (id_sala, numero) VALUES ('S2 ', 15);
INSERT INTO SALA (id_sala, numero) VALUES ('S3 ', 8);



INSERT INTO CURSO (id_curso, NOME, ID_SALA) VALUES ('01 ', 'WORD', 'S1 ');
INSERT INTO CURSO (ID_CURSO, NOME, ID_SALA) VALUES ('02 ', 'EXCEL', 'S1 ');
INSERT INTO CURSO (ID_CURSO, NOME, ID_SALA) VALUES ('03 ', 'LINUX', 'S2 ');
INSERT INTO CURSO (ID_CURSO, NOME, ID_SALA) VALUES ('04 ', 'POWERPOINT', 'S3 ');
INSERT INTO CURSO (ID_CURSO, NOME, id_sala) VALUES ('05 ', 'COREL', 'S3 ');
INSERT INTO CURSO (ID_CURSO, NOME, ID_SALA) VALUES ('06 ', 'ACCESS', 'S3 ');
SELECT*FROM AULA


INSERT INTO PROFESSOR (ID_PROF, NOME) VALUES ('02 ', 'ANA LUCIA');
INSERT INTO PROFESSOR (ID_PROF, NOME) VALUES ('03 ', 'CLAUDIO');
INSERT INTO PROFESSOR (ID_PROF, NOME) VALUES ('04 ', 'ALOISIO');

INSERT INTO ALOCACAO (ID_PROF, ID_CURSO) VALUES ('01 ', '01 ');
INSERT INTO ALOCACAO (ID_PROF, ID_CURSO) VALUES ('01 ', '02 ');
INSERT INTO ALOCACAO (ID_PROF, ID_CURSO) VALUES ('02 ', '03 ');
INSERT INTO ALOCACAO (id_prof, ID_CURSO) VALUES ('03 ', '04 ');
INSERT INTO ALOCACAO (ID_PROF, ID_CURSO) VALUES ('03 ', '05 ');
INSERT INTO ALOCACAO (ID_PROF, ID_CURSO) VALUES ('04 ', '06 ');
INSERT INTO ALOCACAO (ID_PROF, ID_CURSO) VALUES ('01 ', '05 ');

INSERT INTO ALUNO (ID_ALUNO, NOME) VALUES ('001', 'PAULO');
INSERT INTO ALUNO (id_aluno, NOME) VALUES ('002', 'FELIPE');
INSERT INTO ALUNO (id_aluno, NOME) VALUES ('003', 'DANIEL');
INSERT INTO ALUNO (ID_ALUNO, NOME) VALUES ('004', 'ANA CLAUDIA');
INSERT INTO ALUNO (id_aluno, NOME) VALUES ('005', 'PEDRO');

INSERT INTO TURMA (ID_curso, ID_TURMA) VALUES ('01 ', 'A ');
INSERT INTO TURMA (ID_curso, ID_TURMA) VALUES ('02 ', 'A ');
INSERT INTO TURMA (ID_curso, ID_TURMA) VALUES ('01 ', 'B ');
INSERT INTO TURMA (ID_curso, ID_TURMA) VALUES ('03 ', 'A ');
INSERT INTO TURMA (id_curso, id_turma) VALUES ('04 ', 'A ');
INSERT INTO TURMA (id_curso, id_turma) VALUES ('05 ', 'A ');
INSERT INTO TURMA (id_curso, id_turma) VALUES ('05 ', 'B ');


INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES ('01 ', 'A ', '001');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES ('01 ', 'A ', '002');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES ('01 ', 'A ', '003');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA,ID_ALUNO) VALUES ('02 ', 'A ', '001');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES ('02 ', 'A ', '004');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES ('02 ', 'A ', '005');

INSERT INTO ALUNO (id_aluno, NOME) VALUES ('002', 'FELIPE');
INSERT INTO ALUNO (id_aluno, NOME) VALUES ('003', 'DANIEL');
INSERT INTO ALUNO (id_aluno, NOME) VALUES ('004', 'ANA CLAUDIA');
INSERT INTO ALUNO (id_aluno, NOME) VALUES ('005', 'PEDRO');

INSERT INTO TURMA (id_curso,id_turma) VALUES ('01 ', 'A ');
INSERT INTO TURMA (id_curso,id_turma) VALUES ('02 ', 'A ');
INSERT INTO TURMA (id_curso,id_curso) VALUES ('01 ', 'B ');
INSERT INTO TURMA (id_curso,id_turma) VALUES ('03 ', 'A ');
INSERT INTO TURMA (id_curso,id_turma) VALUES ('04 ', 'A ');
INSERT INTO TURMA (id_curso,id_turma) VALUES ('05 ', 'A ');
INSERT INTO TURMA (id_curso, ID_TURMA) VALUES ('05 ', 'B ');

INSERT AULA (ID_PROF,ID_CURSO,DIA,HORA)VALUES ('01','01','A',3,10);
INSERT AULA (ID_PROF,ID_CURSO,DIA,HORA)VALUES ('01','01','B',4,10);
INSERT AULA (ID_PROF,ID_CURSO,DIA,HORA)VALUES ('02','03','A',3,14);
INSERT AULA (ID_PROF,ID_CURSO,DIA,HORA)VALUES ('03','04','A',5,14);
INSERT AULA (ID_PROF,ID_CURSO,DIA,HORA)VALUES ('01','02','A',3,16);
INSERT AULA (ID_PROF,ID_PROF,DIA,HORA)VALUES ('01','05','A',6,14);
INSERT AULA (ID_PROF,ID_PROF,DIA,HORA)VALUES ('02','05','B',4,8);
no


INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES (01 , 'A ', '1');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES (01 , 'A ', '2');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES (01 , 'A ',' 3');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES (02 , 'A ', '1');
INSERT INTO INSCRICAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES (02 , 'A', '4');
INSERT INTO INSCRIiCAO (ID_CURSO, ID_TURMA, ID_ALUNO) VALUES (02 , 'A ', '5');

select curso.id_curso,aluno.nome
from aluno
inner join  curso on aluno.nome=curso.id_curso;
select*from INSCRICAO